### PR TITLE
adds ember-data@1.13.8 support

### PR DESCRIPTION
**Pull request by makepanic**
This commit adds a rewrite of the hal serializer to support the latest jsonapi serializer.
It's using methods on the serializer instead of creating normalizer/serializer/extractor instances and calling its functions. These classes and their corresponding unit tests were removed.

It only works with ember-data > `1.13.5` because it's using the updated `extractId` jsonapi serializer method. (It was a "breaking" change introduced with https://github.com/emberjs/data/pull/3477)

### CODE REVIEW

**Comment by bantic** [comment]
Awesome, thanks — I'll take a look.
If you could update the ember-try scenarios to add ones pinning ember-data to the first working version as well as beta and canary that would be great, but either way I'll review it this evening

**Comment by bantic** [comment]
@makepanic I updated this locally (see https://github.com/201-created/ember-data-hal-9000/commit/b7d46b2841b69794de03e92af84099255b0d562a) to use newest ember-qunit for testing and set up scenarios for testing with ember & ember data in release, beta and canary channels.

Does https://github.com/201-created/ember-data-hal-9000/commit/b7d46b2841b69794de03e92af84099255b0d562a look reasonable to you? If so I will add it on top of your PR here and go ahead and merge it in and cut a new non-backwards-compatible release for this HAL adapter for modern ember/data.

**Comment by makepanic** [comment]
I copied the ember-data@1.13.5 `extractId` method to make it work on ember-data@1.13.4 .
In addition, I modified the ember-try config to use ember-data@1.13.4

**Comment by bantic** [comment]
@makepanic I cherry-picked your commit and have it in #25. That PR also includes some updates like:
  * `ember-qunit` 0.4.9 (necessary for running some of the unit tests with newer ember data)
  * updated ember-cli
  * fixed some tests that were failing on newer ember-data
  * ember-try scenarios for ember-data 1.13.4, 1.13.9, ember#release (w/ ember-data 2.0.0-beta.1), ember#beta, ember#canary

Would you mind giving it a try with your app? You can try it by specifying `0.3.0-beta.2` as the version for `ember-data-hal-9000` in your ember-cli app.

**Comment by makepanic** [comment]
Good work.
I tried `0.3.0-beta.2` and it looks like it's working as expected.

**Comment by bantic** [comment]
closing as this code was merged via a separate branch

**Pull request closed without merging**
